---
# SPDX-FileCopyrightText: JÃ¼rgen MÃ¼lbert
#
# SPDX-License-Identifier: MIT

name: All Source Files

on: # yamllint disable-line rule:truthy
  push:
  release:
    types: [published, edited]

jobs:
  check_commit_msg:
    outputs:
      commit_message: ${{ steps.get_message.outputs.message }}
    name: Check if the workflow has been disabled.
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ§° Checkout Source Code"
        uses: actions/checkout@v3.5.2 # v3.5.2

      - name: Get commit message
        id: get_message
        run: echo "message=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_OUTPUT
  linux:
    needs: check_commit_msg
    name: All Source Files
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: get_version
        shell: bash
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

      - name: "ðŸ§° Check out code"
        uses: actions/checkout@v3.5.2 # v3.5.2

      - name: Create 7z Release
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: ./
          pathTarget: ./jmbde-macos-${{ steps.get_version.outputs.VERSION }}-source-all.7z

      - name: "Upload artifact"
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: jmbde-macos-${{ steps.get_version.outputs.VERSION }}-source-all.7z
          path: jmbde-macos-${{ steps.get_version.outputs.VERSION }}-source-all.7z

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.7.0
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: jmbde-macos-${{ steps.get_version.outputs.VERSION }}-source-all.7z
          asset_name: jmbde-macos-${{ steps.get_version.outputs.VERSION }}-source-all.7z
          tag: ${{ github.ref }}
          overwrite: true
